###
# SignUp
###
POST /api/users/auth/signup
Host: {{ host }}
Authorization: {{ token }}

{
  "name": "Adrian",
  "lastName": "Capote",
  "email": "servimav@yahoo.com",
  "mobilePhone": "55555555",
  "password": "password"
}

###
# Signin
###
POST /api/users/auth/signin
Host: {{ host }}

{
  "mobilePhone": "53375180",
  "password": "password"
}

###
# Profile
###
GET /api/users/auth/profile
Host: {{ host }}
Authorization: {{ token }}