###
# App Token
###
GET /application/token/1
Host: {{ host }}

###
# Setup
###
GET /application/setup
Host: {{ host }}
Authorization: {{ token }}

###
# Setup Settings
###
PATCH /application/setup/save-settings
Host: {{ host }}
Authorization: {{ token }}